create or replace table `pacc-raw-data.BASEVN_HRM.employee` (
    id string,
    metatype string,
    code string,
    first_name string,
    last_name string,
    title string,
    is_primary string,
    user_id string,
    email string,
    gender string,
    phone string,
    dob_day string,
    dob_month string,
    dob_year string,
    tax_id string,
    insurance_id string,
    basic_salary string,
    salary string,
    team_id string,
    timesheet_id string,
    office_id string,
    employee_type_id string,
    area_id string,
    position_id string,
    payroll_policy_id string,
    is_terminated string,
    terminated_date string,
    start_date string,
    official_start_date string,
    form ARRAY<
      STRUCT<
        id string,
        name string,
        type string,
        placeholder string,
        enabled int64,
        required int64,
        options array<string>,
        group_id string,
        value string,
        display string        
        >>,
    last_update string,
    name string,
    type string,
    bank_number string,
    bank_name string,
    bank_branch string,
    bank_holder string,
    profile_marital string,
    profile_pob string,
    profile_nationality string,
    profile_permanent_residence string,
    profile_m2 string,
    profile_m3 string,
    profile_p1 string,
    profile_p2 string,
    profile_p3 string,
    profile_p4 string,
    profile_p5 string,
    profile_note string,
    loaded_date timestamp

)

partition by date(loaded_date)