create or replace table `pacc-raw-data.IPOS_SALE.dm_membership` (
    membership_id string,
    membership_name string,
    membership_type_id string,
    dob datetime,
    phone string,
    address string,
    active int64,
    workstation_id int64,
    user_id string,
    shelf datetime,
    email string,
    note string,
    membership_code string,
    membership_password string,
    firstlogin int64,
    card_info_id string,
    send_sms_dob int64,
    send_sms_log int64,
    year_sms_dob int64,
    send_email_dob int64,
    send_email_log int64,
    year_email_dob int64,
    membership_image bytes,
    converter_date datetime
)