create or replace table `pacc-raw-data.BASEVN_EHIRING.candidate` (
    id string,
    first_name string,
    last_name string,
    email string,
    name string,
    status string,
    disp_name string,
    prefix string,
    title string,
    display_title string,
    phone string,
    dob_day string,
    dob_month string,
    dob_year string,
    gender string,
    ssn string,
    address string,
    cvs array<string>,
    score string,
    evaluations string,
    opening_id string,
    opening_export string,
    tags array<string>,
    medium string,
    fields ARRAY<
      STRUCT<
        id string,
        value string,
        display string,
        type string,
        name string,
        placeholder string
      >>, 
    form array<string>,
    stage_id string,
    stage_name string,
    last_time_stage int64,
    source string,
    campaign string,
    since string,
    last_update string,
    metatype string,
    assign_username string,
    interview_count int64,
    last_interview int64,
    last_stage_before_failed string,
    reason string,
    reason_id string,
    time_apply string,
    time_offered string,
    time_hired string,
    time_rejected string,
    time_campaign_qualified string,
    loaded_date timestamp
)

partition by date(loaded_date)