create or replace table `pacc-raw-data.BASEVN_EHIRING.contact` (
   id string,
   type string,
   hid string,
   token string,
   first_name string,
   last_name string,
   score string,
   sources string,
   source_id string,
   campaigns string,
   tags string,
   phone string,
   changelogs string,
   abs_link string,
   ns_id string,
   image string,
   name string,
   email string,
   title string,
   address string,
   dob string,
   dob_year string,
   gender string,
   stats string,
   content string,
   fields string, 
   form string,
   candidates ARRAY< STRUCT<
       id string,
       name string,
       type string,
       abslink string,
       status_display string,
       codename string,
       owners array<string>,
       creator string,
       candidate_id string,
       candidate_link string,
       scores array<int64>,
       since int64
     >>,
   candidate ARRAY< STRUCT<
       id string,
       name string,
       type string,
       abslink string,
       status_display string,
       codename string,
       owners array<string>,
       creator string,
       candidate_id string,
       candidate_link string,
       scores array<int64>,
       since int64
     >>,
   files ARRAY< STRUCT<
       id string,
       name string,
       url string
     >>,
   since string,
   apply_time string,
   last_update string,
   highlight string,
   loaded_date timestamp
)

partition by date(loaded_date)