import sys, os
import datetime
from google.cloud import bigquery

sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../dbconnector")
import ipos_crm_flow,big_query, loader_format 

brand='BGN'
schema='IPOS_CRM_'+brand
table='member_vouchers'

#data_types
data_types =  {
  'affiliate_discount_extra': int,				
  'voucher_campaign_id': str,				
  'voucher_description': str,				
  'has_sale_manager': int,				
  'is_all_item': int,				
  'amount_order_over': int,				
  'pos_id': str,				
  'date_hash': str,				
  'affiliate_id': str,				
  'voucher_campaign_name': str,				
  'time_hour_day': int,				
  'dm_pos_parent':	{
      'Ws_Sip_Server': str,				
      'Msg_Up_Membership': str,				
      'Using_Ipos_Otp': str,				
      'App_Id': str,				
      'Booking_Type': str,				
      'Using_Cloud_Loyalty': str,				
      'Estimate_Complete_Order_Time': str,				
      'Checkin_Time': str,				
      'Manager_Email_List': str,				
      'Company_Id': str,				
      'Limit_Eat_Count_Per_Day': str,				
      'name': str,				
      'Hotline': str,				
      'Manager_App_Id': str,				
      'Limit_Pay_Amount_Per_Day': str,				
      'Sms_Partner': str,				
      'is_send_sms': str,				
      'Pos_Feature': str,				
      'Logo_Image': str,				
      'Pass_Sip_Server': str,				
      'id': str,				
      'Brand_Name': str,				
      'Member_Parnter_Id': str,				
      'is_gift_point': str,				
      'Direct_List': str,				
      'Msg_Member_Bad_Rate': str,				
      'pos_type': str,				
      'Manager_Phone': str,				
      'ahamove_id': str,				
      'image': str,				
      'description': str	      
  },				
  'discount_type': int,				
  'item_id_list': str,				
  'min_quantity_discount': int,				
  'date_start': datetime.datetime,			
  'discount_extra': int,				
  'date_created': datetime.datetime,			
  'item_type_id_list': str,				
  'voucher_code': str,				
  'status': str,				
  'used_discount_amount': int,				
  'buyer_info': int,				
  'affiliate_discount_type': int,				
  'affiliate_discount_amount': int,				
  'affiliate_used_total_amount': int,				
  'used_pos_id': int,				
  'list_pos':	[
    {
      'Image_Path_Thumb': str,
      'Image_Path': str,
      'Pos_Address': str,
      'Pos_Name': str,
      'Phone_Number': str,
      'Pos_Parent': str,
      'Id': int
    }      
  ],				
  'requied_member': int,				
  'is_delivery': int,				
  'is_ots': int,				
  'time_date_week': int,				
  'discount_max': int,				
  'list_pos_id': str,				
  'discount_one_item': int,				
  'is_coupon': int,				
  'used_member_info': str,				
  'apply_item_id': str,				
  'only_coupon': int,				
  'loaded_date': datetime.datetime,			
  'apply_item_type': str,				
  'pos_parent': str,				
  'discount_per_item': int,				
  'number_item_free': int,				
  'number_item_buy': int,				
  'same_price': int,				
  'used_bill_amount': int,				
  'used_date': str,				
  'membership_id': str,				
  'date_end': datetime.datetime,			
  'discount_amount': int,				
  'used_sale_tran_id': str,				
  'preferential_type': str,				
  'limit_discount_item': int

}

nested_schema_dm_pos_parent = [
    bigquery.SchemaField("Ws_Sip_Server", "STRING"),				
    bigquery.SchemaField("Msg_Up_Membership", "STRING"),				
    bigquery.SchemaField("Using_Ipos_Otp", "STRING"),				
    bigquery.SchemaField("App_Id", "STRING"),				
    bigquery.SchemaField("Booking_Type", "STRING"),				
    bigquery.SchemaField("Using_Cloud_Loyalty", "STRING"),				
    bigquery.SchemaField("Estimate_Complete_Order_Time", "STRING"),				
    bigquery.SchemaField("Checkin_Time", "STRING"),				
    bigquery.SchemaField("Manager_Email_List", "STRING"),				
    bigquery.SchemaField("Company_Id", "STRING"),				
    bigquery.SchemaField("Limit_Eat_Count_Per_Day", "STRING"),				
    bigquery.SchemaField("name", "STRING"),				
    bigquery.SchemaField("Hotline", "STRING"),				
    bigquery.SchemaField("Manager_App_Id", "STRING"),				
    bigquery.SchemaField("Limit_Pay_Amount_Per_Day", "STRING"),				
    bigquery.SchemaField("Sms_Partner", "STRING"),				
    bigquery.SchemaField("is_send_sms", "STRING"),				
    bigquery.SchemaField("Pos_Feature", "STRING"),				
    bigquery.SchemaField("Logo_Image", "STRING"),				
    bigquery.SchemaField("Pass_Sip_Server", "STRING"),				
    bigquery.SchemaField("id", "STRING"),				
    bigquery.SchemaField("Brand_Name", "STRING"),				
    bigquery.SchemaField("Member_Parnter_Id", "STRING"),				
    bigquery.SchemaField("is_gift_point", "STRING"),				
    bigquery.SchemaField("Direct_List", "STRING"),				
    bigquery.SchemaField("Msg_Member_Bad_Rate", "STRING"),				
    bigquery.SchemaField("pos_type", "STRING"),				
    bigquery.SchemaField("Manager_Phone", "STRING"),				
    bigquery.SchemaField("ahamove_id", "STRING"),				
    bigquery.SchemaField("image", "STRING"),				
    bigquery.SchemaField("description", "STRING")	   
]

nested_schema_list_pos = [
    bigquery.SchemaField("Id", "INTEGER"),
    bigquery.SchemaField("Phone_Number", "STRING"),
    bigquery.SchemaField("Pos_Name", "STRING"),
    bigquery.SchemaField("Pos_Parent", "STRING"),
    bigquery.SchemaField("Pos_Address", "STRING"),
    bigquery.SchemaField("Image_Path", "STRING"),
    bigquery.SchemaField("Image_Path_Thumb", "STRING"),
]

# Define the top-level schema with the nested field
schema1 = [
    bigquery.SchemaField("affiliate_discount_extra","INTEGER"),				
    bigquery.SchemaField("voucher_campaign_id","STRING"),				
    bigquery.SchemaField("voucher_description","STRING"),				
    bigquery.SchemaField("has_sale_manager","INTEGER"),				
    bigquery.SchemaField("is_all_item","INTEGER"),				
    bigquery.SchemaField("amount_order_over","INTEGER"),				
    bigquery.SchemaField("pos_id","STRING"),				
    bigquery.SchemaField("date_hash","STRING"),				
    bigquery.SchemaField("affiliate_id","STRING"),				
    bigquery.SchemaField("voucher_campaign_name","STRING"),				
    bigquery.SchemaField("time_hour_day","INTEGER"),	
    bigquery.SchemaField("dm_pos_parent", "RECORD", fields=nested_schema_dm_pos_parent),
    bigquery.SchemaField("discount_type", "INTEGER"),				
    bigquery.SchemaField("item_id_list", "STRING"),				
    bigquery.SchemaField("min_quantity_discount", "INTEGER"),				
    bigquery.SchemaField("date_start", "DATETIME"),			
    bigquery.SchemaField("discount_extra", "INTEGER"),				
    bigquery.SchemaField("date_created", "DATETIME"),			
    bigquery.SchemaField("item_type_id_list", "STRING"),				
    bigquery.SchemaField("voucher_code", "STRING"),				
    bigquery.SchemaField("status", "STRING"),				
    bigquery.SchemaField("used_discount_amount", "INTEGER"),				
    bigquery.SchemaField("buyer_info", "INTEGER"),				
    bigquery.SchemaField("affiliate_discount_type", "INTEGER"),				
    bigquery.SchemaField("affiliate_discount_amount", "INTEGER"),				
    bigquery.SchemaField("affiliate_used_total_amount", "INTEGER"),				
    bigquery.SchemaField("used_pos_id", "STRING"),    
    bigquery.SchemaField("list_pos", "RECORD", mode="REPEATED", fields=nested_schema_list_pos),    
    bigquery.SchemaField('requied_member', "INTEGER"),				
    bigquery.SchemaField('is_delivery', "INTEGER"),				
    bigquery.SchemaField('is_ots', "INTEGER"),				
    bigquery.SchemaField('time_date_week', "INTEGER"),				
    bigquery.SchemaField('discount_max', "INTEGER"),				
    bigquery.SchemaField('list_pos_id', "STRING"),				
    bigquery.SchemaField('discount_one_item', "INTEGER"),				
    bigquery.SchemaField('is_coupon', "INTEGER"),				
    bigquery.SchemaField('used_member_info', "STRING"),				
    bigquery.SchemaField('apply_item_id', "STRING"),				
    bigquery.SchemaField('only_coupon', "INTEGER"),				
    bigquery.SchemaField('apply_item_type', "STRING"),				
    bigquery.SchemaField('pos_parent', "STRING"),				
    bigquery.SchemaField('discount_per_item', "INTEGER"),				
    bigquery.SchemaField('number_item_free', "INTEGER"),				
    bigquery.SchemaField('number_item_buy', "INTEGER"),				
    bigquery.SchemaField('same_price', "INTEGER"),				
    bigquery.SchemaField('used_bill_amount', "INTEGER"),				
    bigquery.SchemaField('used_date', "DATETIME"),				
    bigquery.SchemaField('membership_id', "STRING"),				
    bigquery.SchemaField('date_end', "DATETIME"),			
    bigquery.SchemaField('discount_amount', "INTEGER"),				
    bigquery.SchemaField('used_sale_tran_id', "STRING"),				
    bigquery.SchemaField('preferential_type', "STRING"),				
    bigquery.SchemaField('limit_discount_item', "INTEGER"),
    bigquery.SchemaField('loaded_date', "TIMESTAMP")
    
]

job_config = bigquery.LoadJobConfig(schema=schema1)

#execute
source_output=ipos_crm_flow.crm_get_full_list(brand,table)
source_output_sorted = loader_format.cast_data_types(source_output,data_types)

big_query.full_refresh_bq_insert_from_json2(source_output_sorted,schema,table_id=table,job_config=job_config)
