(
    membership_id string,
    loaded_date timestamp,
    voucher_code string,
    voucher_campaign_id float64,
    voucher_campaign_name string,
    voucher_description string,
    pos_parent string,
    pos_id float64,
    date_created string,
    date_start string,
    date_end string,
    date_hash string,
    amount_order_over float64,
    discount_type float64,
    discount_amount float64,
    discount_extra float64,
    is_all_item float64,
    item_type_id_list string,
    status float64,
    buyer_info string,
    affiliate_id float64,
    affiliate_discount_type float64,
    affiliate_discount_amount float64,
    affiliate_discount_extra float64,
    affiliate_used_total_amount float64,
    used_date string,
    used_discount_amount float64,
    used_bill_amount float64,
    used_member_info string,
    used_pos_id float64,
    used_sale_tran_id string,
    dm_pos_parent 
        struct<
            `App_Id` string, 
            `Booking_Type` int64, 
            `Brand_Name` string, 
            `Checkin_Time` int64, 
            `Company_Id` string, 
            `Direct_List` string, 
            `Estimate_Complete_Order_Time` int64, 
            `Limit_Eat_Count_Per_Day` int64, 
            `Limit_Pay_Amount_Per_Day` int64, 
            `Logo_Image` string, 
            `Manager_App_Id` string, 
            `Manager_Email_List` string, 
            `Manager_Phone` int64, 
            `Member_Parnter_Id` int64, 
            `Msg_Member_Bad_Rate` int64, 
            `Msg_Up_Membership` string, 
            `Pass_Sip_Server` string, 
            `Pos_Feature` int64, 
            `Sms_Partner` string, 
            `Using_Cloud_Loyalty` int64, 
            `Using_Ipos_Otp` int64, 
            `Ws_Sip_Server` string, 
            `ahamove_id` string, 
            `description` string, 
            `id` string, 
            `image` string, 
            `is_gift_point` int64, 
            `is_send_sms` int64, 
            `name` string, 
            `pos_type` int64
        >,
    list_pos array<
        struct<
            `Id` int64, 
            `Image_Path` string, 
            `Image_Path_Thumb` string, 
            `Phone_Number` string, 
            `Pos_Address` string, 
            `Pos_Name` string, 
            `Pos_Parent` string
        >
    >,
    is_delivery float64,
    is_ots float64,
    requied_member float64,
    discount_max float64,
    list_pos_id string,
    item_id_list string,
    discount_one_item float64,
    is_coupon float64,
    only_coupon float64,
    apply_item_id string,
    apply_item_type string,
    number_item_buy float64,
    number_item_free float64,
    same_price float64,
    time_hour_day float64,
    time_date_week float64,
    limit_discount_item float64,
    min_quantity_discount float64,
    preferential_type float64,
    has_sale_manager float64,
    discount_per_item float64,
    __index_level_0__	int64
)

partition by date(loaded_date)