create or replace table `pacc-raw-data.IPOS_CRM_5WINE.member_vouchers` (
    membership_id string,
    loaded_date timestamp,
    voucher_code string,
    voucher_campaign_id float64,
    voucher_campaign_name string,
    voucher_description string,
    pos_parent string,
    pos_id float64,
    date_created string,
    date_start string,
    date_end string,
    date_hash string,
    amount_order_over float64,
    discount_type float64,
    discount_amount float64,
    discount_extra float64,
    is_all_item float64,
    item_type_id_list string,
    status float64,
    buyer_info string,
    affiliate_id float64,
    affiliate_discount_type float64,
    affiliate_discount_amount float64,
    affiliate_discount_extra float64,
    affiliate_used_total_amount float64,
    used_date string,
    used_discount_amount float64,
    used_bill_amount float64,
    used_member_info string,
    used_pos_id float64,
    used_sale_tran_id string,
    dm_pos_parent array<
        struct<
            app_id string, 
            booking_type int64, 
            brand_name string, 
            checkin_time int64, 
            company_id string, 
            direct_list string, 
            estimate_complete_order_time int64, 
            limit_eat_count_per_day int64, 
            limit_pay_amount_per_day int64, 
            logo_image string, 
            manager_app_id string, 
            manager_email_list string, 
            manager_phone int64, 
            member_parnter_id int64, 
            msg_member_bad_rate int64, 
            msg_up_membership string, 
            pass_sip_server string, 
            pos_feature int64, sms_partner 
            string, using_cloud_loyalty int64, 
            using_ipos_otp int64, 
            ws_sip_server string, 
            ahamove_id string, 
            description string, 
            id string, 
            image string, 
            is_gift_point int64, 
            is_send_sms int64, 
            name string, 
            pos_type int64
        >
    >,
    list_pos array<
        struct<
            id int64, 
            image_path string, 
            image_path_thumb string, 
            phone_number string, 
            pos_address string, 
            pos_name string, 
            pos_parent string
        >
    >,
    is_delivery float64,
    is_ots float64,
    requied_member float64,
    discount_max float64,
    list_pos_id string,
    item_id_list string,
    discount_one_item float64,
    is_coupon float64,
    only_coupon float64,
    apply_item_id string,
    apply_item_type string,
    number_item_buy float64,
    number_item_free float64,
    same_price float64,
    time_hour_day float64,
    time_date_week float64,
    limit_discount_item float64,
    min_quantity_discount float64,
    preferential_type float64,
    has_sale_manager float64,
    discount_per_item float64,
    __index_level_0__	int64,
)

partition by date(loaded_date)