(
    id string,
    phone_number int64,
    pos_parent string,
    name string,
    birthday string,
    email string,
    address array<
      struct<
          id string,
          user_id string,
          alias_name string,
          full_address string,
          extend_address string,
          district string,
          city string,
          country string,
          city_id string,
          district_id string,
          longitude float64,
          latitude float64,
          created_at string
      >    
    >,
    membership_type_id string,
    membership_type_name string,
    gender int64,
    city_id int64,
    city_name string,
    user_groups string,
    facebook_messenger_id string,
    facebook_join_at string,
    zalo_id string,
    is_zalo_follow int64,
    zalo_join_at string,
    zalo_last_msg_id string,
    zalo_last_msg_at string,
    point float64,
    payment_amount float64,
    point_amount float64,
    eat_times int64,
    first_eat_date string,
    last_eat_date string,
    update_at string,
    last_pos int64,
    last_pos_name string,
    birth_month int64,
    age int64,
    created_by string,
    created_at string,
    membership_id_new int64,
    membership_type_change_at string,
    ignore_marketing_message int64,
    membership_id string,
    tags array<string>,
    loaded_date timestamp
) partition by date(loaded_date)