create or replace table `pacc-raw-data.IPOS_SALE.dm_membership` (
    MEMBERSHIP_ID string,
    MEMBERSHIP_NAME string,
    MEMBERSHIP_TYPE_ID string,
    DOB datetime,
    PHONE string,
    ADDRESS string,
    ACTIVE INT64,
    WORKSTATION_ID int64,
    USER_ID string,
    SHELF datetime,
    EMAIL string,
    NOTE string,
    MEMBERSHIP_CODE string,
    MEMBERSHIP_PASSWORD string,
    FIRSTLOGIN int64,
    CARD_INFO_ID string,
    SEND_SMS_DOB int64,
    SEND_SMS_LOG int64,
    YEAR_SMS_DOB int64,
    SEND_EMAIL_DOB int64,
    SEND_EMAIL_LOG int64,
    YEAR_EMAIL_DOB int64,
    MEMBERSHIP_IMAGE bytes,
    CONVERTER_DATE datetime,
    LOADED_DATE timestamp
)